services:
  orientation-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
      cache_from: []
    image: ${LOCAL_REGISTRY}:5002/orientation-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
    
  orientation:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/orientation:${TAG}
